# The overall format is standard TOML format, v0.5.0.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/"
# The modid of the mod
modId="templatemod"
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}"
 # A display name for the mod
displayName="Template Mod"
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/yooksi/forge-1.15.2"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="examplemod.png"
# A text field displayed in the mod UI
credits="Thanks for this example mod goes to Java"
# A text field displayed in the mod UI
authors="yooksi"
# The description text for the mod (multi line!)
description='''Sample description'''
